# Site settings
title: Catullus
email: a_waves@163.com
description: a Latin poet of the late Roman Republic
url: "http://wangyn.net/" # the base hostname & protocol for your site
baseurl: ""

# Build settings
markdown: kramdown
#permalink: /:title/

sass: 
  style: compressed

version: 1.0

exclude: ['README.md', '.*', 'Gemfile']

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag


excerpt_separator: <!-- more -->


#disqus-shortname: webjeda-demo
#analytics: UA-83979019-1